### PR TITLE
Release - fix rolled back invite deletion

### PR DESCRIPTION
**Pull request by hobbitronics**
### Fixed
- invite delete was being rolled back

---

### Code Checklist
- [ ] Documentation (README, goswagger, etc.)
- [x] Unit tests created or updated
- [x] Run `gofmt`
- [x] Run `make swaggerspec`

### CODE REVIEW

**Comment by briskt** [comment]
> ### Added
> * add TestPolicyUser_InviteExpired
> * add TestDestroyIfExpired
> * add policyUserInviteExpired listener

IMHO, these things don't need to be listed in a release PR. They're implementation details that aren't visible to a user of the app. But we haven't really established any norms or expectations either, so I could be on my own with this.

**Comment by briskt** [comment]
> ### Code Checklist
> * [ ]  Documentation (README, goswagger, etc.)
> * [x]  Unit tests created or updated
> * [ ]  Run `gofmt`
> * [x]  Run `make swaggerspec`

No `gofmt`?

**Review by briskt — APPROVED** [review]

**Comment by hobbitronics** [comment]
> > ### Code Checklist
> > 
> > * [ ]   Documentation (README, goswagger, etc.)
> > * [x]   Unit tests created or updated
> > * [ ]   Run `gofmt`
> > * [x]   Run `make swaggerspec`
> 
> No `gofmt`?

I don't usually run the command explicitly, but my ide does formatting of the files I edit. It used to mess up the swagger comments, but I think it stopped since updating go.

**Comment by briskt** [comment]
> > > ### Code Checklist
> > > 
> > > * [ ]    Documentation (README, goswagger, etc.)
> > > * [x]    Unit tests created or updated
> > > * [x]    Run `gofmt`
> > > * [x]    Run `make swaggerspec`
> > 
> > 
> > No `gofmt`?
> 
> I don't usually run the command explicitly, but my ide does formatting of the files I edit. It used to mess up the swagger comments, but I think it stopped since updating go.

We can probably remove that one from the checklist. I think I added it when you were bouncing between computers and one of them didn't have the IDE configured. Or something like that.

**Pull request merged**
